#version: '3.8'

# env:
#   ENV_NAME: ${{ github.ref_name }}
#   #secrets
#   MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#   MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
#   #variabili
#   MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
#   MYSQL_USER : ${{ vars.MYSQL_USER }}
#   ALPACA_MARKET_FEED : ${{ vars.ALPACA_MARKET_FEED }}
#   ENV_MARKET : ${{ vars.ENV_MARKET }}
#   ENV_ORDERS : ${{ vars.ENV_ORDERS }}
#   ENV_TRADING : ${{ vars.ENV_TRADING }}
#   LOG_LEVEL : ${{ vars.LOG_LEVEL }}


services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT : ${MYSQL_PORT}
    ports:
      - "3306:3306"
    networks:
      - trading-net
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  dbmanager:
    image: expovin/dbmanager:${DBMANAGER_VERSION}
    container_name: dbmanager
    build:
      context: .
      dockerfile: DBManager/Dockerfile
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - trading-net
    environment:
      - DB_HOST=mysql
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  cachemanager:
    image: expovin/cachemanager:${CACHEMANAGER_VERSION}
    container_name: cachemanager
    build:
      context: .
      dockerfile: cacheManager/Dockerfile
    restart: unless-stopped
    ports:
      - "3006:3006"
    networks:
      - trading-net
    volumes:
      - shared_cache_data:/app/cache
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      dbmanager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  alertingservice:
    image: expovin/alertingservice:${ALERTINGSERVICE_VERSION}
    container_name: alertingservice
    build:
      context: .
      dockerfile: alertingService/Dockerfile
    restart: unless-stopped
    ports:
      - "3008:3008"
    networks:
      - trading-net
    depends_on:
      dbmanager:
        condition: service_healthy
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
      - BACKTESTMODE=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  capitalmanager:
    image: expovin/capitalmanager:${CAPITALMANAGER_VERSION}
    container_name: capitalmanager
    build:
      context: .
      dockerfile: capitalManager/Dockerfile
    restart: unless-stopped
    ports:
      - "3009:3009"
    networks:
      - trading-net
    depends_on:
      dbmanager:
        condition: service_healthy
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
      - ENV_ORDERS=${ENV_ORDERS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # strategyutils:
  #   image: expovin/strategyutils:${STRATEGYUTILS_VERSION}
  #   container_name: strategyutils
  #   build:
  #     context: .
  #     dockerfile: strategyUtils/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "3007:3007"
  #   networks:
  #     - trading-net
  #   environment:
  #     - CACHEMANAGER_URL=http://cachemanager:3006
  #     - LOG_LEVEL=${LOG_LEVEL}
  #   depends_on:
  #     cachemanager:
  #       condition: service_healthy
  #     dbmanager:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3007/health"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5

  livemarketlistener:
    image: expovin/livemarketlistener:${LIVEMARKETLISTENER_VERSION}
    container_name: livemarketlistener
    build:
      context: .
      dockerfile: LiveMarketListener/Dockerfile
    restart: unless-stopped
    ports:
      - "3012:3012"
    networks:
      - trading-net
    depends_on:
      cachemanager:
        condition: service_healthy
      dbmanager:
        condition: service_healthy
      sma:
        condition: service_healthy
      capitalmanager:
        condition: service_healthy
      alertingservice:
        condition: service_healthy
      # strategyutils:
      #   condition: service_healthy
      marketsimulator:
        condition: service_healthy
      ordersimulator:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DBMANAGER_URL=http://dbmanager:3002
      - ENV_MARKET=${ENV_MARKET}
      - ENV_ORDERS=${ENV_ORDERS}
      - FEED=${ALPACA_MARKET_FEED}
      - SMA_URL=http://sma:3010
      - CAPITAL_MANAGER_URL=http://capitalmanager:3009
      - ALERTINGMANAGER_URL=http://alertingservice:3008

  orderlistner:
    image: expovin/orderlistner:${ORDERLISTNER_VERSION}
    container_name: orderlistner
    build:
      context: .
      dockerfile: orderListner/Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3005"
    networks:
      - trading-net
    depends_on:
      cachemanager:
        condition: service_healthy
      dbmanager:
        condition: service_healthy
      alertingservice:
        condition: service_healthy
      marketsimulator:
        condition: service_healthy
      ordersimulator:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DBMANAGER_URL=http://dbmanager:3002
      - ENV_TRADING=${ENV_TRADING}
      - ALERTINGMANAGER_URL=http://alertingservice:3008



  sma:
    image: expovin/sma:${SMA_VERSION}
    container_name: sma
    build:
      context: .
      dockerfile: strategies/sma/Dockerfile
    restart: unless-stopped
    ports:
      - "3010:3010"
    networks:
      - trading-net
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      dbmanager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 10s
      timeout: 10s
      retries: 5



  # Sezione docker per la simulazione
  ordersimulator:
    image: expovin/ordersimulator:${ORDERSIMULATOR_VERSION}
    container_name: ordersimulator
    build:
      context: .
      dockerfile: orderSimulator/Dockerfile
    restart: unless-stopped
    ports:
      - "3004:3004"
    networks:
      - trading-net
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DBMANAGER_URL=http://dbmanager:3002
    depends_on:
      dbmanager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 10s
      timeout: 10s
      retries: 5


  marketsimulator:
    image: expovin/marketsimulator:${MARKETSIMULATOR_VERSION}
    container_name: marketsimulator
    build:
      context: .
      dockerfile: marketsimulator/Dockerfile
    restart: unless-stopped
    ports:
      - "3003:3003"
    networks:
      - trading-net
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DBMANAGER_URL=http://dbmanager:3002
    depends_on:
      dbmanager:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  shared_cache_data:
    external: true

networks:
  trading-net:
    name:  trading-net
    driver: bridge