#version: '3.8'

# env:
#   ENV_NAME: ${{ github.ref_name }}
#   #secrets
#   MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#   MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
#   #variabili
#   MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
#   MYSQL_USER : ${{ vars.MYSQL_USER }}
#   ALPACA_MARKET_FEED : ${{ vars.ALPACA_MARKET_FEED }}
#   ENV_MARKET : ${{ vars.ENV_MARKET }}
#   ENV_ORDERS : ${{ vars.ENV_ORDERS }}
#   ENV_TRADING : ${{ vars.ENV_TRADING }}
#   LOG_LEVEL : ${{ vars.LOG_LEVEL }}

  dbmanager:
    build:
      context: .
      dockerfile: DBManager/Dockerfile

  cachemanager:
    build:
      context: .
      dockerfile: cacheManager/Dockerfile

  alertingservice:
    build:
      context: .
      dockerfile: alertingService/Dockerfile

  capitalmanager:
    build:
      context: .
      dockerfile: capitalManager/Dockerfile

  livemarketlistener:
    build:
      context: .
      dockerfile: LiveMarketListener/Dockerfile

  orderlistner:
    build:
      context: .
      dockerfile: orderListner/Dockerfile


  sma:
    build:
      context: .
      dockerfile: strategies/sma/Dockerfile

  sltp:
    build:
      context: .
      dockerfile: strategies/sltp/Dockerfile



