#version: '3.8'

# env:
#   ENV_NAME: ${{ github.ref_name }}
#   #secrets
#   MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#   MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
#   #variabili
#   MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
#   MYSQL_USER : ${{ vars.MYSQL_USER }}
#   ALPACA_MARKET_FEED : ${{ vars.ALPACA_MARKET_FEED }}
#   ENV_MARKET : ${{ vars.ENV_MARKET }}
#   ENV_ORDERS : ${{ vars.ENV_ORDERS }}
#   ENV_TRADING : ${{ vars.ENV_TRADING }}
#   LOG_LEVEL : ${{ vars.LOG_LEVEL }}


services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT : ${MYSQL_PORT}
      MYSQL_HOST : ${MYSQL_HOST}
    ports:
      - "3306:3306"
    networks:
      - trading-net
    depends_on:
      redis:
          condition: service_healthy
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - trading-net
    command: ["redis-server", "--appendonly", "yes", "--save", "300", "10","--dir","/data"]
    volumes:
      - redis-data:/data
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  dbmanager:
    image: expovin/dbmanager:${DBMANAGER_VERSION}
    container_name: dbmanager
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - trading-net
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_URL=redis://redis:6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  cachemanager:
    image: expovin/cachemanager:${CACHEMANAGER_VERSION}
    container_name: cachemanager
    restart: unless-stopped
    ports:
      - "3006:3006"
    networks:
      - trading-net
    volumes:
      - shared_cache_data:/app/cache
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_URL=redis://redis:6379
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
    depends_on:
      dbmanager:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  alertingservice:
    image: expovin/alertingservice:${ALERTINGSERVICE_VERSION}
    container_name: alertingservice
    restart: unless-stopped
    ports:
      - "3008:3008"
    networks:
      - trading-net
    depends_on:
      dbmanager:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
      - BACKTESTMODE=false
      - REDIS_URL=redis://redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  capitalmanager:
    image: expovin/capitalmanager:${CAPITALMANAGER_VERSION}
    container_name: capitalmanager
    restart: unless-stopped
    ports:
      - "3009:3009"
    networks:
      - trading-net
    depends_on:
      dbmanager:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - MARKETSIMULATOR_URL=http://marketsimulator:3003
      - ORDERSIMULATOR_URL=http://ordersimulator:3004
      - LOG_LEVEL=${LOG_LEVEL}
      - ENV_ORDERS=${ENV_ORDERS}
      - REDIS_URL=redis://redis:6379
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  livemarketlistener:
    image: expovin/livemarketlistener:${LIVEMARKETLISTENER_VERSION}
    container_name: livemarketlistener
    restart: unless-stopped
    ports:
      - "3012:3012"
    networks:
      - trading-net
    depends_on:
      cachemanager:
        condition: service_healthy
      dbmanager:
        condition: service_healthy
      redis:
        condition: service_healthy
      sma:
        condition: service_healthy
      sltp:
        condition: service_healthy
      capitalmanager:
        condition: service_healthy
      alertingservice:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DBMANAGER_URL=http://dbmanager:3002
      - REDIS_URL=redis://redis:6379
      - ENV_MARKET=${ENV_MARKET}
      - ENV_ORDERS=${ENV_ORDERS}
      - FEED=${ALPACA_MARKET_FEED}
      - SMA_URL=http://sma:3010
      - SLTP_URL=http://sltp:3011
      - CAPITAL_MANAGER_URL=http://capitalmanager:3009
      - ALERTINGMANAGER_URL=http://alertingservice:3008
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}

  orderlistner:
    image: expovin/orderlistner:${ORDERLISTNER_VERSION}
    container_name: orderlistner
    restart: unless-stopped
    ports:
      - "3005:3005"
    networks:
      - trading-net
    depends_on:
      cachemanager:
        condition: service_healthy
      dbmanager:
        condition: service_healthy
      redis:
        condition: service_healthy
      alertingservice:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DBMANAGER_URL=http://dbmanager:3002
      - ENV_TRADING=${ENV_TRADING}
      - ENV_ORDERS=${ENV_ORDERS}
      - ALERTINGMANAGER_URL=http://alertingservice:3008
      - LIVEMARKETMANAGER_URL=http://livemarketlistener:3012
      - REDIS_URL=redis://redis:6379
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}


  sma:
    image: expovin/sma:${SMA_VERSION}
    container_name: sma
    restart: unless-stopped
    ports:
      - "3010:3010"
    networks:
      - trading-net
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_URL=redis://redis:6379
      - CACHEMANAGER_URL=http://cachemanager:3006
    depends_on:
      dbmanager:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  sltp:
    image: expovin/sltp:${SLTP_VERSION}
    container_name: sltp
    restart: unless-stopped
    ports:
      - "3011:3011"
    networks:
      - trading-net
    environment:
      - DBMANAGER_URL=http://dbmanager:3002
      - LOG_LEVEL=${LOG_LEVEL}
      - ENV_ORDERS=${ENV_ORDERS}
      - REDIS_URL=redis://redis:6379
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
    depends_on:
      dbmanager:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3011/health"]
      interval: 10s
      timeout: 10s
      retries: 5


  # Sezione docker per la simulazione

volumes:
  mysql_data:
  redis-data:
  shared_cache_data:
    external: true

networks:
  trading-net:
    name:  trading-net
    driver: bridge