apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cachemanager
spec:
  selector:
    app: cachemanager
  ports:
    - port: 3006
      targetPort: 3006
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dbmanager
spec:
  selector:
    app: dbmanager
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alertingservice
spec:
  selector:
    app: alertingservice
  ports:
    - port: 3008
      targetPort: 3008
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: capitalmanager
spec:
  selector:
    app: capitalmanager
  ports:
    - port: 3009
      targetPort: 3009
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: strategy-utils
spec:
  selector:
    app: strategy-utils
  ports:
    - port: 3007
      targetPort: 3007
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: livemarketlistener
spec:
  selector:
    app: livemarketlistener
  ports:
    - port: 3012
      targetPort: 3012
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sma
spec:
  selector:
    app: sma
  ports:
    - port: 3010
      targetPort: 3010
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: orderlistner
spec:
  selector:
    app: orderlistner
  ports:
    - port: 3011
      targetPort: 3011
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ordersimulator
spec:
  selector:
    app: ordersimulator
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: marketsimulator
spec:
  selector:
    app: marketsimulator
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP